baseURL = "https://gorri-zuria.es/"
languageCode = "es-es"
title = "Pe単a Gorri Zuria - Athletic Bilbao (Villanueva Ca単ada - Madrid)"
theme = "gorri-zuria"
#googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    # Provide some metadata for search and indexing services
    description = "Web oficial de Pe単a Gorri Zuria - Athletic Club Bilbao (Villanueva Ca単ada - Madrid)"

[Author]
    name = "Felipe RM"
    email = "gorrizuriaathletic@gmail.com"

# counter analytics: see https://counter.dev/setup.html
[counter]
enable = true
username = "GorriZuria" # username counter.dev