[build]
    publish = "public"
    command = "hugo --minify --gc"

[build.enviroment]
    HUGO_VERSION = "0.89.0"
    HUGO_ENV = "production"
    HUGO_ENABLEGITINFO = "true"

[headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  Referrer-Policy = "same-origin"
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"